/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=.wrangler/types/wrangler.jsonc --env-file=wrangler.types.env --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings types/cloudflare-bindings.d.ts` (hash: f9401c03860b0ca71ee54eca771ed46b)
interface __BaseEnv_CloudflareBindings {
	CACHE_KV: KVNamespace;
	DB: D1Database;
	IMAGES: ImagesBinding;
	SESSION_SECRET: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SESSION_SECRET">> {}
}
